### ISSUE TITLE
Customer home page blank. data  is not retrieving

### ISSUE THREAD

**Issue by HammadNawaz35** [Mufaddal5253110/FoodOn_FoodDelivery_by_Androrealm#1]
When chef post dish it is not showing in customer page and page is blank .app crashing .Skipping layout.no adapter attached

**Comment by Mufaddal5253110** [comment]
It's because I have restricted the rules to read from firebase , you have to connect with your firebase first.

**Comment by HammadNawaz35** [comment]
> It's because I have restricted the rules to read from firebase , you have to connect with your firebase first.

Dear firebase is connected  and rules are set true ..users chef and customer r registering successfully ,dishes r also posted but data not showing in customer page.???  Plz reply its request

**Comment by Mufaddal5253110** [comment]
Can you just post the log error you are facing, and have you check the realtime database rules

**Comment by HammadNawaz35** [comment]
> Can you just post the log error you are facing, and have you check the realtime database rules

![Screenshot_20210321-095614](https://user-images.githubusercontent.com/81030278/111894319-c51a6400-8a2b-11eb-8bff-85b6fa18bc66.png)
U can check firebase rule
